/**
 * LitGap - Reporter Module
 * Generate Markdown analysis reports
 * 
 * @module reporter
 * @version 1.0.0
 * 
 * Ported from: generate_report.py
 */

var Reporter = {
  
  /**
   * Generate complete Markdown report
   * 
   * @param {Array} userPapers - User's papers from Parser
   * @param {Array} recommendations - Recommendations from Analyzer (with scores)
   * @param {Object} citationStats - Statistics from API module
   * @returns {string} Markdown formatted report
   */
  generateReport: function(userPapers, recommendations, citationStats) {
    Zotero.debug("Reporter: Generating Markdown report...");
    
    const report = [];
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    
    // Header
    report.push('# 🔬 LitGap Analysis Report');
    report.push(`**Generated**: ${dateStr}\n`);
    report.push('---\n');
    
    // Library Overview (Detailed)
    report.push('## 📚 Your Library Overview\n');
    report.push(this._generateLibraryStats(userPapers, citationStats));
    report.push('\n---\n');
    
    // Recommendations with smart grouping
    report.push('## 🎯 Recommended Papers (Knowledge Gaps)\n');
    report.push(`Found **${recommendations.length}** papers you may have missed.\n`);
    report.push(this._generateRecommendations(recommendations));
    
    // About section
    report.push('\n---\n');
    report.push(this._generateAboutSection());
    
    // Footer
    report.push('\n---\n');
    report.push(`*Generated by LitGap v1.0 on ${dateStr}*\n`);
    
    Zotero.debug(`Reporter: Report generated (${report.join('').length} characters)`);
    
    return report.join('\n');
  },
  
  /**
   * Generate detailed library statistics
   * 
   * @private
   * @param {Array} userPapers - User's papers
   * @param {Object} citationStats - Citation statistics
   * @returns {string} Statistics section
   */
  _generateLibraryStats: function(userPapers, citationStats) {
    const stats = [];
    
    // Basic counts
    stats.push(`- **Papers analyzed**: ${userPapers.length}`);
    
    // DOI coverage
    const withDOI = userPapers.filter(p => p.doi).length;
    const doiPercent = userPapers.length > 0 
      ? Math.round((withDOI / userPapers.length) * 100) 
      : 0;
    stats.push(`- **With DOI**: ${withDOI} (${doiPercent}%)`);
    
    // Year range
    const years = userPapers
      .map(p => parseInt(p.year))
      .filter(y => !isNaN(y));
    if (years.length > 0) {
      const minYear = Math.min(...years);
      const maxYear = Math.max(...years);
      stats.push(`- **Year range**: ${minYear} - ${maxYear}`);
    }
    
    // Type distribution
    const types = {};
    userPapers.forEach(p => {
      types[p.type] = (types[p.type] || 0) + 1;
    });
    const mostCommonType = Object.entries(types)
      .sort((a, b) => b[1] - a[1])[0];
    if (mostCommonType) {
      stats.push(`- **Most common type**: ${mostCommonType[0]} (${mostCommonType[1]})`);
    }
    
    // Citation statistics
    if (citationStats) {
      stats.push(`- **Citations analyzed**: ${citationStats.unique_citations} unique papers`);
    }
    
    return stats.join('\n');
  },
  
  /**
   * Generate recommendations section with smart grouping
   * 
   * @private
   * @param {Array} recommendations - Sorted recommendations with scores
   * @returns {string} Recommendations section
   */
  _generateRecommendations: function(recommendations) {
    if (recommendations.length === 0) {
      return '\n*No recommendations found. Your library is well-covered!*\n';
    }
    
    const sections = [];
    
    // Identify priority papers: Top 3 + Early Influential (if not in Top 3)
    const top3Ids = new Set(recommendations.slice(0, 3).map(p => p.paperId));
    const earlyInfluential = recommendations.find(p => 
      p.isEarlyInfluential && !top3Ids.has(p.paperId)
    );
    
    const priorityPapers = recommendations.slice(0, 3);
    if (earlyInfluential) {
      priorityPapers.push(earlyInfluential);
    }
    
    const priorityIds = new Set(priorityPapers.map(p => p.paperId));
    const recommendedPapers = recommendations.filter(p => !priorityIds.has(p.paperId));
    
    // Priority Reading section
    sections.push('### 📌 Priority Reading\n');
    if (earlyInfluential && !top3Ids.has(earlyInfluential.paperId)) {
      sections.push('*Top 3 by score + Early influential work*\n');
    } else {
      sections.push('*Top 3 by score*\n');
    }
    
    priorityPapers.forEach((paper, idx) => {
      const originalRank = recommendations.findIndex(p => p.paperId === paper.paperId) + 1;
      sections.push(this._formatPaper(paper, originalRank));
    });
    
    // Recommended Reading section
    if (recommendedPapers.length > 0) {
      sections.push('\n### 📖 Recommended Reading\n');
      recommendedPapers.forEach(paper => {
        const rank = recommendations.findIndex(p => p.paperId === paper.paperId) + 1;
        sections.push(this._formatPaper(paper, rank));
      });
    }
    
    return sections.join('\n');
  },
  
  /**
   * Format a single paper entry
   * 
   * @private
   * @param {Object} paper - Paper with scores
   * @param {number} rank - Original rank in recommendations
   * @returns {string} Formatted paper entry
   */
  _formatPaper: function(paper, rank) {
    const lines = [];
    
    // Title with rank
    lines.push(`\n#### ${rank}. ${paper.title}\n`);
    
    // Early Influential label (if applicable)
    if (paper.isEarlyInfluential) {
      lines.push(`📚 **Early influential work** (${paper.year}, ${paper.citationCount} citations, cited by ${paper.mentioned_count} papers)\n`);
    }
    
    // Score
    lines.push(`**Score**: ${paper.totalScore.toFixed(1)}/100`);
    lines.push(`- Mentioned by: ${paper.mentioned_count} of your papers`);
    lines.push(`- Total citations: ${paper.citationCount.toLocaleString()}`);
    lines.push(`- Year: ${paper.year || 'N/A'}\n`);
    
    // Why recommended (concise)
    const reasons = this._generateReasons(paper);
    lines.push(`**Why recommended**: ${reasons}\n`);
    
    lines.push('---');
    
    return lines.join('\n');
  },
  
  /**
   * Generate concise recommendation reasons
   * 
   * @private
   * @param {Object} paper - Paper with scores
   * @returns {string} Concise reasons
   */
  _generateReasons: function(paper) {
    const reasons = [];
    
    // Mention frequency
    if (paper.mentioned_count >= 5) {
      reasons.push(`Cited by ${paper.mentioned_count} papers (core literature)`);
    } else {
      reasons.push(`Cited by ${paper.mentioned_count} papers`);
    }
    
    // Impact
    const citations = paper.citationCount || 0;
    if (citations > 500) {
      reasons.push(`${citations.toLocaleString()} citations (high impact)`);
    } else if (citations > 200) {
      reasons.push(`${citations} citations`);
    }
    
    // Recency
    if (paper.recencyScore === 3) {
      reasons.push(`Recent (${paper.year})`);
    } else if (paper.recencyScore === 2) {
      reasons.push(`Relatively recent (${paper.year})`);
    }
    
    return reasons.join('; ');
  },
  
  /**
   * Generate "About This Report" section
   * 
   * @private
   * @returns {string} About section
   */
  _generateAboutSection: function() {
    const lines = [];
    
    lines.push('## 📘 About This Report\n');
    
    lines.push('### What are "knowledge gaps"?\n');
    lines.push('Papers frequently cited by your library but not in your collection. ');
    lines.push('These represent important works you may have overlooked.\n');
    
    lines.push('### How is scoring calculated?\n');
    lines.push('- **Mention frequency**: How many of your papers cite it (highest weight)');
    lines.push('- **Academic impact**: Total citation count');
    lines.push('- **Recency**: Publication year (recent papers get bonus)\n');
    
    lines.push('### About 📚 "Early influential work"\n');
    lines.push('Papers marked with 📚 are among the **earliest in your recommendations** ');
    lines.push('with significant citations. This label is based on **relative analysis** ');
    lines.push('within your library, not absolute field history.\n');
    
    lines.push('**Important**: We identify papers that appear important in YOUR research ');
    lines.push('context, but cannot guarantee they are definitively "pioneering" works ');
    lines.push('in the broader field.\n');
    
    lines.push('### Reading suggestions\n');
    lines.push('1. Start with **Priority Reading** (Top 3 + Early influential)');
    lines.push('2. Skim abstracts of **Recommended Reading**');
    lines.push('3. Focus on papers with highest mention counts (cited by multiple papers in your library)');
    
    return lines.join('\n');
  }
};