/**
 * LitGap - Reporter Module
 * Generate Markdown and HTML analysis reports
 * 
 * @module reporter
 * @version 1.2.0
 * 
 * Ported from: generate_report.py
 * 
 * CHANGELOG:
 * v1.2.0 - Added donation links to Markdown and HTML reports
 * v1.1.0 - Added DOI links, Semantic Scholar links, HTML generation
 * v1.0.0 - Initial implementation
 */

var Reporter = {
  
  /**
   * Generate complete Markdown report with enhanced links
   * 
   * @param {Array} userPapers - User's papers from Parser
   * @param {Array} recommendations - Recommendations from Analyzer (with scores)
   * @param {Object} citationStats - Statistics from API module
   * @returns {string} Markdown formatted report
   */
  generateReport: function(userPapers, recommendations, citationStats) {
    Zotero.debug("Reporter: Generating Markdown report with enhanced links...");
    
    const report = [];
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    
    // Header
    report.push('# 🔬 LitGap Analysis Report');
    report.push(`**Generated**: ${dateStr}\n`);
    report.push('---\n');
    
    // Library Overview
    report.push('## 📊 Your Library Overview\n');
    report.push(this._generateLibraryStats(userPapers, citationStats));
    report.push('\n---\n');
    
    // Recommendations
    report.push('## 🎯 Recommended Papers (Knowledge Gaps)\n');
    report.push(`Found **${recommendations.length}** papers you may have missed.\n`);
    report.push(this._generateRecommendations(recommendations));
    
    // About section
    report.push('\n---\n');
    report.push(this._generateAboutSection());
    
    // Footer
    report.push('\n---\n');
    report.push(`*Generated by LitGap v1.1 on ${dateStr}*\n`);
    
    Zotero.debug(`Reporter: Markdown report generated (${report.join('').length} characters)`);
    
    return report.join('\n');
  },
  
  /**
   * Generate HTML version of the report
   * 
   * @param {Array} userPapers - User's papers from Parser
   * @param {Array} recommendations - Recommendations from Analyzer (with scores)
   * @param {Object} citationStats - Statistics from API module
   * @returns {string} HTML formatted report
   */
  generateHTMLReport: function(userPapers, recommendations, citationStats) {
    Zotero.debug("Reporter: Generating HTML report...");
    
    const now = new Date();
    const dateStr = now.toISOString().split('T')[0];
    
    const html = [];
    
    // HTML header with styling
    html.push('<!DOCTYPE html>');
    html.push('<html lang="en">');
    html.push('<head>');
    html.push('  <meta charset="UTF-8">');
    html.push('  <meta name="viewport" content="width=device-width, initial-scale=1.0">');
    html.push('  <title>LitGap Analysis Report</title>');
    html.push('  <style>');
    html.push(this._getHTMLStyles());
    html.push('  </style>');
    html.push('</head>');
    html.push('<body>');
    html.push('  <div class="container">');
    
    // Header
    html.push('    <header>');
    html.push('      <h1> 🔬 LitGap Analysis Report</h1>');
    html.push(`      <p class="date">Generated: ${dateStr}</p>`);
    html.push('    </header>');
    
    // Library Overview
    html.push('    <section class="library-overview">');
    html.push('      <h2> 📊 Your Library Overview</h2>');
    html.push(this._generateLibraryStatsHTML(userPapers, citationStats));
    html.push('    </section>');
    
    // Recommendations
    html.push('    <section class="recommendations">');
    html.push('      <h2> 🎯 Recommended Papers (Knowledge Gaps)</h2>');
    html.push(`      <p class="summary">Found <strong>${recommendations.length}</strong> papers you may have missed.</p>`);
    html.push(this._generateRecommendationsHTML(recommendations));
    html.push('    </section>');
    
    // About section
    html.push('    <section class="about">');
    html.push('      <h2> 📖 About This Report</h2>');
    html.push(this._generateAboutSectionHTML());
    html.push('    </section>');
    
    // Footer
    html.push('    <footer>');
    html.push(`      <p>Generated by <strong>LitGap v1.1</strong> on ${dateStr}</p>`);
    html.push('    </footer>');
    
    html.push('  </div>');
    html.push('</body>');
    html.push('</html>');
    
    Zotero.debug(`Reporter: HTML report generated (${html.join('').length} characters)`);
    
    return html.join('\n');
  },
  
  /**
   * Generate detailed library statistics (Markdown)
   * 
   * @private
   * @param {Array} userPapers - User's papers
   * @param {Object} citationStats - Citation statistics
   * @returns {string} Statistics section
   */
  _generateLibraryStats: function(userPapers, citationStats) {
    const stats = [];
    
    stats.push(`- **Papers analyzed**: ${userPapers.length}`);
    
    const withDOI = userPapers.filter(p => p.doi).length;
    const doiPercent = userPapers.length > 0 
      ? Math.round((withDOI / userPapers.length) * 100) 
      : 0;
    stats.push(`- **With DOI**: ${withDOI} (${doiPercent}%)`);
    
    const years = userPapers.map(p => parseInt(p.year)).filter(y => !isNaN(y));
    if (years.length > 0) {
      const minYear = Math.min(...years);
      const maxYear = Math.max(...years);
      stats.push(`- **Year range**: ${minYear} - ${maxYear}`);
    }
    
    const types = {};
    userPapers.forEach(p => types[p.type] = (types[p.type] || 0) + 1);
    const mostCommonType = Object.entries(types).sort((a, b) => b[1] - a[1])[0];
    if (mostCommonType) {
      stats.push(`- **Most common type**: ${mostCommonType[0]} (${mostCommonType[1]})`);
    }
    
    if (citationStats) {
      stats.push(`- **Citations analyzed**: ${citationStats.unique_citations} unique papers`);
    }
    
    return stats.join('\n');
  },
  
  /**
   * Generate library statistics (HTML)
   * 
   * @private
   */
  _generateLibraryStatsHTML: function(userPapers, citationStats) {
    const html = [];
    html.push('      <ul class="stats-list">');
    
    html.push(`        <li><strong>Papers analyzed:</strong> ${userPapers.length}</li>`);
    
    const withDOI = userPapers.filter(p => p.doi).length;
    const doiPercent = Math.round((withDOI / userPapers.length) * 100);
    html.push(`        <li><strong>With DOI:</strong> ${withDOI} (${doiPercent}%)</li>`);
    
    const years = userPapers.map(p => parseInt(p.year)).filter(y => !isNaN(y));
    if (years.length > 0) {
      const minYear = Math.min(...years);
      const maxYear = Math.max(...years);
      html.push(`        <li><strong>Year range:</strong> ${minYear} - ${maxYear}</li>`);
    }
    
    const types = {};
    userPapers.forEach(p => types[p.type] = (types[p.type] || 0) + 1);
    const mostCommonType = Object.entries(types).sort((a, b) => b[1] - a[1])[0];
    if (mostCommonType) {
      html.push(`        <li><strong>Most common type:</strong> ${mostCommonType[0]} (${mostCommonType[1]})</li>`);
    }
    
    if (citationStats) {
      html.push(`        <li><strong>Citations analyzed:</strong> ${citationStats.unique_citations} unique papers</li>`);
    }
    
    html.push('      </ul>');
    return html.join('\n');
  },
  
  /**
   * Generate recommendations section (Markdown)
   * 
   * @private
   * @param {Array} recommendations - Sorted recommendations with scores
   * @returns {string} Recommendations section
   */
  _generateRecommendations: function(recommendations) {
    if (recommendations.length === 0) {
      return '\n*No recommendations found. Your library is well-covered!*\n';
    }
    
    const sections = [];
    
    // Identify priority papers
    const top3Ids = new Set(recommendations.slice(0, 3).map(p => p.paperId));
    const earlyInfluential = recommendations.find(p => 
      p.isEarlyInfluential && !top3Ids.has(p.paperId)
    );
    
    const priorityPapers = recommendations.slice(0, 3);
    if (earlyInfluential) {
      priorityPapers.push(earlyInfluential);
    }
    
    const priorityIds = new Set(priorityPapers.map(p => p.paperId));
    const recommendedPapers = recommendations.filter(p => !priorityIds.has(p.paperId));
    
    // Priority Reading
    sections.push('### 📌 Priority Reading\n');
    if (earlyInfluential && !top3Ids.has(earlyInfluential.paperId)) {
      sections.push('*Top 3 by score + Early influential work*\n');
    } else {
      sections.push('*Top 3 by score*\n');
    }
    
    priorityPapers.forEach((paper) => {
      const originalRank = recommendations.findIndex(p => p.paperId === paper.paperId) + 1;
      sections.push(this._formatPaper(paper, originalRank));
    });
    
    // Recommended Reading
    if (recommendedPapers.length > 0) {
      sections.push('\n### 📖 Recommended Reading\n');
      recommendedPapers.forEach(paper => {
        const rank = recommendations.findIndex(p => p.paperId === paper.paperId) + 1;
        sections.push(this._formatPaper(paper, rank));
      });
    }
    
    return sections.join('\n');
  },
  
  /**
   * Generate recommendations (HTML)
   * 
   * @private
   */
  _generateRecommendationsHTML: function(recommendations) {
    if (recommendations.length === 0) {
      return '      <p class="no-results">No recommendations found. Your library is well-covered!</p>';
    }
    
    const html = [];
    
    const top3Ids = new Set(recommendations.slice(0, 3).map(p => p.paperId));
    const earlyInfluential = recommendations.find(p => 
      p.isEarlyInfluential && !top3Ids.has(p.paperId)
    );
    
    const priorityPapers = recommendations.slice(0, 3);
    if (earlyInfluential) {
      priorityPapers.push(earlyInfluential);
    }
    
    const priorityIds = new Set(priorityPapers.map(p => p.paperId));
    const recommendedPapers = recommendations.filter(p => !priorityIds.has(p.paperId));
    
    // Priority Reading
    html.push('      <div class="priority-section">');
    html.push('        <h3> 📌 Priority Reading</h3>');
    if (earlyInfluential && !top3Ids.has(earlyInfluential.paperId)) {
      html.push('        <p class="subtitle">Top 3 by score + Early influential work</p>');
    } else {
      html.push('        <p class="subtitle">Top 3 by score</p>');
    }
    
    priorityPapers.forEach((paper) => {
      const originalRank = recommendations.findIndex(p => p.paperId === paper.paperId) + 1;
      html.push(this._formatPaperHTML(paper, originalRank, true));
    });
    
    html.push('      </div>');
    
    // Recommended Reading
    if (recommendedPapers.length > 0) {
      html.push('      <div class="recommended-section">');
      html.push('        <h3> 📖 Recommended Reading</h3>');
      
      recommendedPapers.forEach(paper => {
        const rank = recommendations.findIndex(p => p.paperId === paper.paperId) + 1;
        html.push(this._formatPaperHTML(paper, rank, false));
      });
      
      html.push('      </div>');
    }
    
    return html.join('\n');
  },
  
  /**
   * Format a single paper entry (Markdown)
   * 
   * @private
   * @param {Object} paper - Paper with scores
   * @param {number} rank - Original rank in recommendations
   * @returns {string} Formatted paper entry
   */
  _formatPaper: function(paper, rank) {
    const lines = [];
    
    // Title with rank
    lines.push(`\n#### ${rank}. ${paper.title}\n`);
    
    // Early Influential label
    if (paper.isEarlyInfluential) {
      lines.push(`📚 **Early influential work** (${paper.year}, ${paper.citationCount} citations, cited by ${paper.mentioned_count} papers)\n`);
    }
    
    // Score and metadata
    lines.push(`**Score**: ${paper.totalScore.toFixed(1)}/100`);
    lines.push(`- Mentioned by: ${paper.mentioned_count} of your papers`);
    lines.push(`- Total citations: ${paper.citationCount.toLocaleString()}`);
    lines.push(`- Year: ${paper.year || 'N/A'}\n`);
    
    // Enhanced Links Section
    lines.push('**Access Links**:');
    
    if (paper.doi) {
      const doi = paper.doi.trim();
      lines.push(`- 📖 DOI: [${doi}](https://doi.org/${encodeURIComponent(doi)})`);
    }
    
    if (paper.paperId) {
      lines.push(`- 📘 [View on Semantic Scholar](https://www.semanticscholar.org/paper/${paper.paperId})`);
    }
    
    const searchQuery = encodeURIComponent(paper.title);
    lines.push(`- 🎯 [Search on Google Scholar](https://scholar.google.com/scholar?q=${searchQuery})\n`);
    
    // Why recommended
    const reasons = this._generateReasons(paper);
    lines.push(`**Why recommended**: ${reasons}\n`);
    
    lines.push('---');
    
    return lines.join('\n');
  },
  
  /**
   * Format a single paper entry (HTML)
   * 
   * @private
   */
  _formatPaperHTML: function(paper, rank, isPriority) {
    const html = [];
    const className = isPriority ? 'paper-card priority' : 'paper-card';
    
    html.push(`        <div class="${className}">`);
    html.push(`          <h4>${rank}. ${this._escapeHTML(paper.title)}</h4>`);
    
    if (paper.isEarlyInfluential) {
      html.push(`          <span class="badge early-influential">📚 Early influential work</span>`);
    }
    
    html.push(`          <div class="score">Score: ${paper.totalScore.toFixed(1)}/100</div>`);
    
    html.push('          <ul class="metadata">');
    html.push(`            <li>Mentioned by: <strong>${paper.mentioned_count}</strong> of your papers</li>`);
    html.push(`            <li>Total citations: <strong>${paper.citationCount.toLocaleString()}</strong></li>`);
    html.push(`            <li>Year: <strong>${paper.year || 'N/A'}</strong></li>`);
    html.push('          </ul>');
    
    // Enhanced links
    html.push('          <div class="links">');
    html.push('            <strong>Access Links:</strong>');
    
    if (paper.doi) {
      const doi = paper.doi.trim();
      html.push(`            <a href="https://doi.org/${encodeURIComponent(doi)}" target="_blank" class="link-btn doi">📄 DOI</a>`);
    }
    
    if (paper.paperId) {
      html.push(`            <a href="https://www.semanticscholar.org/paper/${paper.paperId}" target="_blank" class="link-btn scholar">📘🔍 Semantic Scholar</a>`);
    }
    
    const searchQuery = encodeURIComponent(paper.title);
    html.push(`            <a href="https://scholar.google.com/scholar?q=${searchQuery}" target="_blank" class="link-btn google">🎯 Google Scholar</a>`);
    
    html.push('          </div>');
    
    const reasons = this._generateReasons(paper);
    html.push(`          <p class="reasons"><strong>Why recommended:</strong> ${this._escapeHTML(reasons)}</p>`);
    
    html.push('        </div>');
    
    return html.join('\n');
  },
  
  /**
   * Generate concise recommendation reasons
   * 
   * @private
   * @param {Object} paper - Paper with scores
   * @returns {string} Concise reasons
   */
  _generateReasons: function(paper) {
    const reasons = [];
    
    if (paper.mentioned_count >= 5) {
      reasons.push(`Cited by ${paper.mentioned_count} papers (core literature)`);
    } else {
      reasons.push(`Cited by ${paper.mentioned_count} papers`);
    }
    
    const citations = paper.citationCount || 0;
    if (citations > 500) {
      reasons.push(`${citations.toLocaleString()} citations (high impact)`);
    } else if (citations > 200) {
      reasons.push(`${citations} citations`);
    }
    
    if (paper.recencyScore === 3) {
      reasons.push(`Recent (${paper.year})`);
    } else if (paper.recencyScore === 2) {
      reasons.push(`Relatively recent (${paper.year})`);
    }
    
    return reasons.join('; ');
  },
  
  /**
   * Generate "About This Report" section (Markdown)
   * 
   * @private
   * @returns {string} About section
   */
  _generateAboutSection: function() {
    const lines = [];
    
    lines.push('## 📘 About This Report\n');
    
    lines.push('### What are "knowledge gaps"?\n');
    lines.push('Papers frequently cited by your library but not in your collection. ');
    lines.push('These represent important works you may have overlooked.\n');
    
    lines.push('### How is scoring calculated?\n');
    lines.push('- **Mention frequency**: How many of your papers cite it (highest weight)');
    lines.push('- **Academic impact**: Total citation count');
    lines.push('- **Recency**: Publication year (recent papers get bonus)\n');
    
    lines.push('### About 📚 "Early influential work"\n');
    lines.push('Papers marked with 📚 are among the **earliest in your recommendations** ');
    lines.push('with significant citations. This label is based on **relative analysis** ');
    lines.push('within your library, not absolute field history.\n');
    
    lines.push('**Important**: We identify papers that appear important in YOUR research ');
    lines.push('context, but cannot guarantee they are definitively "pioneering" works ');
    lines.push('in the broader field.\n');
    
    lines.push('### Reading suggestions\n');
    lines.push('1. Start with **Priority Reading** (Top 3 + Early influential)');
    lines.push('2. Click on DOI links to access papers directly (works with Zotero extensions)');
    lines.push('3. Use Semantic Scholar for additional context and related papers');
    lines.push('4. Focus on papers with highest mention counts (cited by multiple papers)');
    
    lines.push('\n---\n');
    lines.push('### 💖“ Support This Project\n');
    lines.push('If LitGap helps your research, consider supporting development:\n');
    lines.push('- [GitHub Sponsors](https://github.com/sponsors/Yu-TingSun)');
    lines.push('- [Ko-fi](https://ko-fi.com/yutingsun)\n');
    lines.push('Your support enables continued development and new features. Thank you! 🙏');
    
    return lines.join('\n');
  },
  
  /**
   * Generate "About This Report" section (HTML)
   * 
   * @private
   */
  _generateAboutSectionHTML: function() {
    const html = [];
    
    html.push('      <div class="about-content">');
    html.push('        <h3>What are "knowledge gaps"?</h3>');
    html.push('        <p>Papers frequently cited by your library but not in your collection. These represent important works you may have overlooked.</p>');
    
    html.push('        <h3>How is scoring calculated?</h3>');
    html.push('        <ul>');
    html.push('          <li><strong>Mention frequency</strong>: How many of your papers cite it (highest weight)</li>');
    html.push('          <li><strong>Academic impact</strong>: Total citation count</li>');
    html.push('          <li><strong>Recency</strong>: Publication year (recent papers get bonus)</li>');
    html.push('        </ul>');
    
    html.push('        <h3>About 📚 "Early influential work"</h3>');
    html.push('        <p>Papers marked with 📚 are among the <strong>earliest in your recommendations</strong> with significant citations. This label is based on <strong>relative analysis</strong> within your library, not absolute field history.</p>');
    html.push('        <p><strong>Important</strong>: We identify papers that appear important in YOUR research context, but cannot guarantee they are definitively "pioneering" works in the broader field.</p>');
    
    html.push('        <h3>Reading suggestions</h3>');
    html.push('        <ol>');
    html.push('          <li>Start with <strong>Priority Reading</strong> (Top 3 + Early influential)</li>');
    html.push('          <li>Click on DOI links to access papers directly (works with Zotero extensions)</li>');
    html.push('          <li>Use Semantic Scholar for additional context and related papers</li>');
    html.push('          <li>Focus on papers with highest mention counts</li>');
    html.push('        </ol>');
    html.push('      </div>');
    
    html.push('      <div class="support-section">');
    html.push('        <h3>💖“ Support This Project</h3>');
    html.push('        <p>If LitGap helps your research, consider supporting development:</p>');
    html.push('        <div class="support-links">');
    html.push('          <a href="https://github.com/sponsors/Yu-TingSun" target="_blank" class="support-btn github">❤️Â GitHub Sponsors</a>');
    html.push('          <a href="https://ko-fi.com/yutingsun" target="_blank" class="support-btn kofi">☕ Ko-fi</a>');
    html.push('        </div>');
    html.push('        <p class="support-note">Your support enables continued development and new features. Thank you! 🙏</p>');
    html.push('      </div>');
    
    return html.join('\n');
  },
  
  /**
   * Get CSS styles for HTML report
   * 
   * @private
   * @returns {string} CSS styles
   */
  _getHTMLStyles: function() {
    return `
* {
  margin: 0;
  padding: 0;
  box-sizing: border-box;
}

body {
  font-family: -apple-system, BlinkMacSystemFont, "Segoe UI", Helvetica, Arial, sans-serif;
  line-height: 1.6;
  color: #24292e;
  background: #f6f8fa;
  padding: 20px;
}

.container {
  max-width: 900px;
  margin: 0 auto;
  background: white;
  padding: 40px;
  border-radius: 8px;
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
}

header {
  text-align: center;
  margin-bottom: 40px;
  padding-bottom: 20px;
  border-bottom: 2px solid #e1e4e8;
}

h1 {
  color: #24292e;
  font-size: 2.5em;
  margin-bottom: 10px;
}

.date {
  color: #586069;
  font-size: 0.9em;
}

h2 {
  color: #24292e;
  font-size: 1.8em;
  margin: 30px 0 20px 0;
  padding-bottom: 10px;
  border-bottom: 1px solid #e1e4e8;
}

h3 {
  color: #0366d6;
  font-size: 1.4em;
  margin: 25px 0 15px 0;
}

h4 {
  color: #24292e;
  font-size: 1.1em;
  margin-bottom: 10px;
}

section {
  margin-bottom: 40px;
}

.stats-list {
  list-style: none;
  padding: 0;
}

.stats-list li {
  padding: 8px 0;
  border-bottom: 1px solid #f6f8fa;
}

.summary {
  font-size: 1.1em;
  color: #586069;
  margin-bottom: 20px;
}

.subtitle {
  font-style: italic;
  color: #586069;
  margin-bottom: 20px;
}

.paper-card {
  background: #f6f8fa;
  border-left: 4px solid #e1e4e8;
  padding: 20px;
  margin-bottom: 20px;
  border-radius: 4px;
  transition: all 0.2s;
}

.paper-card:hover {
  box-shadow: 0 2px 8px rgba(0,0,0,0.1);
  border-left-color: #0366d6;
}

.paper-card.priority {
  background: #fff8e1;
  border-left-color: #fdb71a;
}

.badge {
  display: inline-block;
  padding: 4px 12px;
  margin: 10px 0;
  border-radius: 12px;
  font-size: 0.85em;
  font-weight: 600;
  background: #fff3cd;
  color: #856404;
}

.score {
  font-size: 1.2em;
  font-weight: bold;
  color: #0366d6;
  margin: 10px 0;
}

.metadata {
  list-style: none;
  padding: 0;
  margin: 10px 0;
}

.metadata li {
  padding: 5px 0;
}

.links {
  margin: 15px 0;
}

.link-btn {
  display: inline-block;
  padding: 6px 12px;
  margin: 5px 5px 5px 0;
  background: #0366d6;
  color: white !important;
  text-decoration: none;
  border-radius: 4px;
  font-size: 0.9em;
  transition: background 0.2s;
}

.link-btn:hover {
  background: #0256c7;
}

.link-btn.doi {
  background: #28a745;
}

.link-btn.doi:hover {
  background: #218838;
}

.link-btn.scholar {
  background: #6f42c1;
}

.link-btn.scholar:hover {
  background: #5a32a3;
}

.link-btn.google {
  background: #dc3545;
}

.link-btn.google:hover {
  background: #c82333;
}

.reasons {
  margin-top: 15px;
  padding-top: 15px;
  border-top: 1px solid #e1e4e8;
  color: #586069;
}

.about-content {
  background: #f6f8fa;
  padding: 20px;
  border-radius: 4px;
}

.about-content h3 {
  color: #24292e;
  font-size: 1.2em;
  margin-top: 20px;
}

.about-content p {
  margin: 10px 0;
}

.about-content ul, .about-content ol {
  margin: 10px 0;
  padding-left: 30px;
}

.about-content li {
  margin: 5px 0;
}

.support-section {
  background: linear-gradient(135deg, #667eea 0%, #764ba2 100%);
  color: white;
  padding: 30px;
  border-radius: 8px;
  margin: 30px 0;
  text-align: center;
}

.support-section h3 {
  color: white;
  margin-bottom: 15px;
}

.support-section p {
  margin: 10px 0;
}

.support-links {
  display: flex;
  justify-content: center;
  gap: 15px;
  margin: 20px 0;
  flex-wrap: wrap;
}

.support-btn {
  display: inline-block;
  padding: 12px 24px;
  background: white;
  color: #667eea;
  text-decoration: none;
  border-radius: 6px;
  font-weight: bold;
  transition: transform 0.2s, box-shadow 0.2s;
}

.support-btn:hover {
  transform: translateY(-2px);
  box-shadow: 0 4px 12px rgba(0,0,0,0.2);
}

.support-btn.github {
  background: #ffffff;
  color: #764ba2;
}

.support-btn.kofi {
  background: #ffffff;
  color: #667eea;
}

.support-note {
  font-size: 0.9em;
  opacity: 0.9;
}

footer {
  text-align: center;
  margin-top: 40px;
  padding-top: 20px;
  border-top: 1px solid #e1e4e8;
  color: #586069;
  font-size: 0.9em;
}

@media print {
  body {
    background: white;
    padding: 0;
  }
  
  .container {
    box-shadow: none;
    max-width: 100%;
  }
  
  .link-btn {
    background: #f6f8fa !important;
    color: #0366d6 !important;
    border: 1px solid #0366d6;
  }
}

@media (max-width: 768px) {
  body {
    padding: 10px;
  }
  
  .container {
    padding: 20px;
  }
  
  h1 {
    font-size: 2em;
  }
  
  h2 {
    font-size: 1.5em;
  }
  
  .link-btn {
    display: block;
    margin: 5px 0;
  }
}
    `;
  },
  
  /**
   * Escape HTML special characters
   * 
   * @private
   * @param {string} text - Text to escape
   * @returns {string} Escaped text
   */
  _escapeHTML: function(text) {
    const map = {
      '&': '&amp;',
      '<': '&lt;',
      '>': '&gt;',
      '"': '&quot;',
      "'": '&#039;'
    };
    return text.replace(/[&<>"']/g, m => map[m]);
  }
};
